server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gastro_review
    username: luis
    password: 1622
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: "mysupersecretkeyforjwtsecurity123456"
    expiration-time: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    display-request-duration: true
